services:
     
  nginx:
    networks:
      - "front"
    image: nginx:1.23-alpine
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"

  php:
    networks:
      - "back"
      - "front"
      - "middle"
    image: nginx:1.23-alpine
    volumes:
      - ./web:/usr/share/nginx/html
    deploy:
      replicas:
        3

  redis:
    networks:
      - "back"
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  plantuml:
    networks:
      - "middle"
    image: nginx:1.23-alpine
    restart: always
    ports:
      - "8080:8080"

networks:
  front:
  back:
  middle:

volumes:
  redis_data: {}
