CREATE OR REPLACE PROCEDURE sp_clonetable(p_table VARCHAR2)IS
DECLARE CURSOR c_table (p_colonne VARCHAR2)IS SELECT COLUMN_NAME FROM all_tab_columns WHERE TABLE_NAME=p_table;
v_increment NUMBER;
TYPE COLONNE IS TABLE OF VARCHAR2 INDEX BY BINARY_INTEGER;
tableau COLONNE;
chaine VARCHAR2(1000);
BEGIN
OPEN c_table
LOOP
FETCH c_table BULK COLLECT INTO chaine,tableau(1);
EXIT WHEN c_table%NOTFOUND;
END LOOP;
CLOSE c_table
END;
