#version: "3.3"
services:
     
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
        #    links:
        #- php:php

  php:
    image: windok/php-redis
    restart: always
#    expose:
#      - "9000"
    volumes:
      - ./web:/usr/share/nginx/html
    environment:
      - NOM="fouche"
      - PRENOM="joffrey"
    deploy:
      replicas: 2

  redis:
    image: redis/redis-stack
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redisinsight:
    image: redislabs/redisinsight
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - redisinsight_data:/db

volumes:
  redis_data: {}
  redisinsight_data: {}
