DROP TABLE Client;
DROP TABLE Commande;
CREATE TABLE Client(id INT PRIMARY KEY,prenom VARCHAR2(100),nom VARCHAR2(100),email VARCHAR2(1000),ville VARCHAR2(1000))ON DELETE CASCADE;
CREATE TABLE Commande(id INT PRIMARY KEY, client_id INT REFERENCES Client(id),date_achat DATE, reference VARCHAR2(1000))ON DELETE CASCADE;