CREATE OR REPLACE TRIGGER tr_nb_employe
AFTER INSERT OR UPDATE of DEPTNO OR DELETE
ON EMP
DECLARE
v_depno NUMBER;
BEGIN

IF INSERTING THEN
v_depno:=:new.DEPNO;
UPDATE SUIVI_EMP SET Nom_Emp=Nombre_Emp+1 WHERE DEPTNO=v_depno;
END IF;

IF UPDATING THEN
v_depno:=:old.DEPNO;
UPDATE SUIVI_EMP SET Nom_Emp=Nombre_Emp-1 WHERE DEPTNO=v_depno;
v_depno:=:new.DEPNO;
UPDATE SUIVI_EMP SET Nom_Emp=Nombre_Emp+1 WHERE DEPTNO=v_depno;
END IF;

IF DELETING THEN
v_depno:=:old.DEPNO;
UPDATE SUIVI_EMP SET Nom_Emp=Nombre_Emp-1 WHERE DEPTNO=v_depno;
END IF;

END;