function com_woonoz_gwt_woonoz_Voltaire(){var Q='bootstrap',R='begin',S='gwt.codesvr.com.woonoz.gwt.woonoz.Voltaire=',T='gwt.codesvr=',U='com.woonoz.gwt.woonoz.Voltaire',V='startup',W='DUMMY',X=0,Y=1,Z='iframe',$='javascript:""',_='position:absolute; width:0; height:0; border:none; left: -1000px;',ab=' top: -1000px;',bb='CSS1Compat',cb='<!doctype html>',db='',eb='<html><head><\/head><body><\/body><\/html>',fb='undefined',gb='DOMContentLoaded',hb=50,ib='Chrome',jb='eval("',kb='");',lb='script',mb='javascript',nb='moduleStartup',ob='moduleRequested',pb='com_woonoz_gwt_woonoz_Voltaire',qb='Failed to load ',rb='head',sb='meta',tb='name',ub='com.woonoz.gwt.woonoz.Voltaire::',vb='::',wb='gwt:property',xb='content',yb='=',zb='gwt:onPropertyErrorFn',Ab='Bad handler "',Bb='" for "gwt:onPropertyErrorFn"',Cb='gwt:onLoadErrorFn',Db='" for "gwt:onLoadErrorFn"',Eb='#',Fb='?',Gb='/',Hb='img',Ib='clear.cache.gif',Jb='baseUrl',Kb='com.woonoz.gwt.woonoz.Voltaire.nocache.js',Lb='base',Mb='//',Nb='locale',Ob='fr',Pb='locale=',Qb=7,Rb='&',Sb='__gwt_Locale',Tb='_',Ub='Unexpected exception in locale detection, using default: ',Vb=2,Wb='user.agent',Xb='webkit',Yb='safari',Zb='msie',$b=10,_b=11,ac='ie10',bc=9,cc='ie9',dc=8,ec='ie8',fc='gecko',gc='gecko1_8',hc=3,ic=4,jc='selectingPermutation',kc='com.woonoz.gwt.woonoz.Voltaire.devmode.js',lc='de',mc='25FFB9A4C8B54B0256167544BF4F80B5',nc='6A9F2AE904BF4B0985B46C986FDC9775',oc='7475D231B9A88A9CD73B08A56ED66A23',pc='7A698E282EDAABD74BA1891395C3D44C',qc='8DBB54B672346276A4B00466FF899105',rc='BF70098C2CA3BF5275865E8DE3C3FE89',sc='C03D0C64F7BD584BB147FFB8109B4D10',tc='CF78173A872BA1D73F1E7DCE262AAC13',uc='DF8994106DBCC4F390BD72B2C1DCD143',vc='EBEC9346FE3C25670B75A5C2FC1F4ECC',wc=':',xc='.cache.js',yc='link',zc='rel',Ac='stylesheet',Bc='href',Cc='loadExternalRefs',Dc='gwt/standard/standard.css',Ec='woonozLibrary.css',Fc='skin/jquery-ui/jquery-ui-1.8.18.custom.css',Gc='end',Hc='http:',Ic='file:',Jc='_gwt_dummy_',Kc='__gwtDevModeHook:com.woonoz.gwt.woonoz.Voltaire',Lc='Ignoring non-whitelisted Dev Mode URL: ',Mc=':moduleBase';var q=window;var r=document;t(Q,R);function s(){var a=q.location.search;return a.indexOf(S)!=-1||a.indexOf(T)!=-1}
function t(a,b){if(q.__gwtStatsEvent){q.__gwtStatsEvent({moduleName:U,sessionId:q.__gwtStatsSessionId,subSystem:V,evtGroup:a,millis:(new Date).getTime(),type:b})}}
com_woonoz_gwt_woonoz_Voltaire.__sendStats=t;com_woonoz_gwt_woonoz_Voltaire.__moduleName=U;com_woonoz_gwt_woonoz_Voltaire.__errFn=null;com_woonoz_gwt_woonoz_Voltaire.__moduleBase=W;com_woonoz_gwt_woonoz_Voltaire.__softPermutationId=X;com_woonoz_gwt_woonoz_Voltaire.__computePropValue=null;com_woonoz_gwt_woonoz_Voltaire.__getPropMap=null;com_woonoz_gwt_woonoz_Voltaire.__installRunAsyncCode=function(){};com_woonoz_gwt_woonoz_Voltaire.__gwtStartLoadingFragment=function(){return null};com_woonoz_gwt_woonoz_Voltaire.__gwt_isKnownPropertyValue=function(){return false};com_woonoz_gwt_woonoz_Voltaire.__gwt_getMetaProperty=function(){return null};var u=null;var v=q.__gwt_activeModules=q.__gwt_activeModules||{};v[U]={moduleName:U};com_woonoz_gwt_woonoz_Voltaire.__moduleStartupDone=function(e){var f=v[U].bindings;v[U].bindings=function(){var a=f?f():{};var b=e[com_woonoz_gwt_woonoz_Voltaire.__softPermutationId];for(var c=X;c<b.length;c++){var d=b[c];a[d[X]]=d[Y]}return a}};var w;function A(){B();return w}
function B(){if(w){return}var a=r.createElement(Z);a.src=$;a.id=U;a.style.cssText=_+ab;a.tabIndex=-1;r.body.appendChild(a);w=a.contentDocument;if(!w){w=a.contentWindow.document}w.open();var b=document.compatMode==bb?cb:db;w.write(b+eb);w.close()}
function C(k){function l(a){function b(){if(typeof r.readyState==fb){return typeof r.body!=fb&&r.body!=null}return /loaded|complete/.test(r.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(r.removeEventListener){r.removeEventListener(gb,d,false)}if(e){clearInterval(e)}}}
if(r.addEventListener){r.addEventListener(gb,d,false)}var e=setInterval(function(){if(b()){d()}},hb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=A();var f=e.body;var g;if(navigator.userAgent.indexOf(ib)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(jb));for(var i=X;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(Y,j.length-Y)))}h.appendChild(e.createTextNode(kb));g=e.createElement(lb);g.language=mb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=X;i<c.length;i++){g=e.createElement(lb);g.language=mb;g.text=c[i];f.appendChild(g);d(f,g)}}}
com_woonoz_gwt_woonoz_Voltaire.onScriptDownloaded=function(a){l(function(){m(a)})};t(nb,ob);var n=r.createElement(lb);n.src=k;if(com_woonoz_gwt_woonoz_Voltaire.__errFn){n.onerror=function(){com_woonoz_gwt_woonoz_Voltaire.__errFn(pb,new Error(qb+code))}}r.getElementsByTagName(rb)[X].appendChild(n)}
com_woonoz_gwt_woonoz_Voltaire.__startLoadingFragment=function(a){return G(a)};com_woonoz_gwt_woonoz_Voltaire.__installRunAsyncCode=function(a){var b=A();var c=b.body;var d=b.createElement(lb);d.language=mb;d.text=a;c.appendChild(d);c.removeChild(d)};function D(){var c={};var d;var e;var f=r.getElementsByTagName(sb);for(var g=X,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(tb),k;if(j){j=j.replace(ub,db);if(j.indexOf(vb)>=X){continue}if(j==wb){k=i.getAttribute(xb);if(k){var l,m=k.indexOf(yb);if(m>=X){j=k.substring(X,m);l=k.substring(m+Y)}else{j=k;l=db}c[j]=l}}else if(j==zb){k=i.getAttribute(xb);if(k){try{d=eval(k)}catch(a){alert(Ab+k+Bb)}}}else if(j==Cb){k=i.getAttribute(xb);if(k){try{e=eval(k)}catch(a){alert(Ab+k+Db)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};u=d;com_woonoz_gwt_woonoz_Voltaire.__errFn=e}
function F(){function e(a){var b=a.lastIndexOf(Eb);if(b==-1){b=a.length}var c=a.indexOf(Fb);if(c==-1){c=a.length}var d=a.lastIndexOf(Gb,Math.min(c,b));return d>=X?a.substring(X,d+Y):db}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=r.createElement(Hb);b.src=a+Ib;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Jb);if(a!=null){return a}return db}
function h(){var a=r.getElementsByTagName(lb);for(var b=X;b<a.length;++b){if(a[b].src.indexOf(Kb)!=-1){return e(a[b].src)}}return db}
function i(){var a=r.getElementsByTagName(Lb);if(a.length>X){return a[a.length-Y].href}return db}
function j(){var a=r.location;return a.href==a.protocol+Mb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==db){k=h()}if(k==db){k=i()}if(k==db&&j()){k=e(r.location.href)}k=f(k);return k}
function G(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return com_woonoz_gwt_woonoz_Voltaire.__moduleBase+a}
function H(){var i=[];var j=X;function k(a,b){var c=i;for(var d=X,e=a.length-Y;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var l=[];var m=[];function n(a){var b=m[a](),c=l[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(u){u(a,d,b)}throw null}
m[Nb]=function(){var b=null;var c=Ob;try{if(!b){var d=location.search;var e=d.indexOf(Pb);if(e>=X){var f=d.substring(e+Qb);var g=d.indexOf(Rb,e);if(g<X){g=d.length}b=d.substring(e+Qb,g)}}if(!b){b=__gwt_getMetaProperty(Nb)}if(!b){b=q[Sb]}if(b){c=b}while(b&&!__gwt_isKnownPropertyValue(Nb,b)){var h=b.lastIndexOf(Tb);if(h<X){b=null;break}b=b.substring(X,h)}}catch(a){alert(Ub+a)}q[Sb]=c;return b||Ob};l[Nb]={de:X,'default':Y,fr:Vb};m[Wb]=function(){var a=navigator.userAgent.toLowerCase();var b=r.documentMode;if(function(){return a.indexOf(Xb)!=-1}())return Yb;if(function(){return a.indexOf(Zb)!=-1&&(b>=$b&&b<_b)}())return ac;if(function(){return a.indexOf(Zb)!=-1&&(b>=bc&&b<_b)}())return cc;if(function(){return a.indexOf(Zb)!=-1&&(b>=dc&&b<_b)}())return ec;if(function(){return a.indexOf(fc)!=-1||b>=_b}())return gc;return db};l[Wb]={gecko1_8:X,ie10:Y,ie8:Vb,ie9:hc,safari:ic};__gwt_isKnownPropertyValue=function(a,b){return b in l[a]};com_woonoz_gwt_woonoz_Voltaire.__getPropMap=function(){var a={};for(var b in l){if(l.hasOwnProperty(b)){a[b]=n(b)}}return a};com_woonoz_gwt_woonoz_Voltaire.__computePropValue=n;q.__gwt_activeModules[U].bindings=com_woonoz_gwt_woonoz_Voltaire.__getPropMap;t(Q,jc);if(s()){return G(kc)}var o;try{k([lc,ec],mc);k([Ob,Yb],nc);k([Ob,ec],oc);k([Ob,gc],pc);k([Ob,cc],qc);k([lc,Yb],rc);k([Ob,ac],sc);k([lc,cc],tc);k([lc,ac],uc);k([lc,gc],vc);o=i[n(Nb)][n(Wb)];var p=o.indexOf(wc);if(p!=-1){j=parseInt(o.substring(p+Y),$b);o=o.substring(X,p)}}catch(a){}com_woonoz_gwt_woonoz_Voltaire.__softPermutationId=j;return G(o+xc)}
function I(){if(!q.__gwt_stylesLoaded){q.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=r.createElement(yc);b.setAttribute(zc,Ac);b.setAttribute(Bc,G(a));r.getElementsByTagName(rb)[X].appendChild(b);__gwt_stylesLoaded[a]=true}}
t(Cc,R);c(Dc);c(Ec);c(Fc);t(Cc,Gc)}
D();com_woonoz_gwt_woonoz_Voltaire.__moduleBase=F();v[U].moduleBase=com_woonoz_gwt_woonoz_Voltaire.__moduleBase;var J=H();if(q){var K=!!(q.location.protocol==Hc||q.location.protocol==Ic);q.__gwt_activeModules[U].canRedirect=K;function L(){var b=Jc;try{q.sessionStorage.setItem(b,b);q.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(K&&L()){var M=Kc;var N=q.sessionStorage[M];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(N)){if(N&&(window.console&&console.log)){console.log(Lc+N)}N=db}if(N&&!q[M]){q[M]=true;q[M+Mc]=F();var O=r.createElement(lb);O.src=N;var P=r.getElementsByTagName(rb)[X];P.insertBefore(O,P.firstElementChild||P.children[X]);return false}}}I();t(Q,Gc);C(J);return true}
com_woonoz_gwt_woonoz_Voltaire.succeeded=com_woonoz_gwt_woonoz_Voltaire();